"""add-PoolStat-table

Revision ID: 0c265e625140
Revises: a653accab1cd
Create Date: 2025-04-01 04:12:27.016675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c265e625140'
down_revision: Union[str, None] = 'a653accab1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poolstats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('launchpad_id', sa.Integer(), nullable=False),
    sa.Column('token0_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token1_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('tvl_usd', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee_tier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('transactions_24h', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('price_change_1h', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('price_change_24h', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('price_change_7d', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('min_price_24h', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('max_price_24h', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['launchpad_id'], ['launchpads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poolstats')
    # ### end Alembic commands ###
