"""add-Trade-table

Revision ID: 81a36c9cc34e
Revises: 0c265e625140
Create Date: 2025-04-01 04:13:48.546898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81a36c9cc34e'
down_revision: Union[str, None] = '0c265e625140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('launchpad_id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.String(length=191), nullable=False),
    sa.Column('amount', sa.String(length=191), nullable=False),
    sa.Column('usd', sa.String(length=191), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default='now()', nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['launchpad_id'], ['launchpads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
