"""add-factory-table

Revision ID: 85ac280f014f
Revises: e81f6e2dd201
Create Date: 2025-04-01 03:57:49.246256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ac280f014f'
down_revision: Union[str, None] = 'e81f6e2dd201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=191), nullable=False),
    sa.Column('chainId', sa.String(length=191), nullable=True),
    sa.Column('foundry', sa.String(length=191), nullable=True),
    sa.Column('contract', sa.String(length=191), nullable=True),
    sa.Column('lock', sa.String(length=191), nullable=True),
    sa.Column('lock_abi', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('factory_abi', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('abi', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factories')
    # ### end Alembic commands ###
