"""add-lunchpad-table

Revision ID: 8cc2b1ad0994
Revises: 85ac280f014f
Create Date: 2025-04-01 04:08:37.865194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc2b1ad0994'
down_revision: Union[str, None] = '85ac280f014f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launchpads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('contract', sa.String(length=44), nullable=True),
    sa.Column('token', sa.String(length=44), nullable=True),
    sa.Column('pool', sa.String(length=44), nullable=True),
    sa.Column('graph', sa.String(length=600), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chainId', sa.String(length=191), nullable=False),
    sa.Column('twitter', sa.String(length=191), nullable=True),
    sa.Column('discord', sa.String(length=191), nullable=True),
    sa.Column('telegram', sa.String(length=191), nullable=True),
    sa.Column('website', sa.String(length=191), nullable=True),
    sa.Column('livestreamId', sa.String(length=191), nullable=True),
    sa.Column('status', sa.String(length=191), nullable=False),
    sa.Column('logo', sa.String(length=191), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('kingofthehill', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launchpads')
    # ### end Alembic commands ###
