"""add-links-to-user

Revision ID: 9a9e8c826b5c
Revises: 81a36c9cc34e
Create Date: 2025-04-01 06:11:00.037927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9e8c826b5c'
down_revision: Union[str, None] = '81a36c9cc34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.String(length=191), nullable=True))
    op.add_column('users', sa.Column('twitter', sa.String(length=191), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'website')
    # ### end Alembic commands ###
