"""adding sales date sales table

Revision ID: e669e06d2e1e
Revises: d0d9b4ce58f7
Create Date: 2025-05-17 08:29:01.620619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e669e06d2e1e'
down_revision: Union[str, None] = 'd0d9b4ce58f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sale_date')
    # ### end Alembic commands ###
