"""users_description

Revision ID: e81f6e2dd201
Revises: 68676db812ad
Create Date: 2025-04-01 03:41:58.575753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e81f6e2dd201'
down_revision: Union[str, None] = '68676db812ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_launchpads_factory_id', table_name='launchpads')
    op.drop_index('ix_launchpads_user_id', table_name='launchpads')
    op.drop_table('launchpads')
    op.drop_table('factories')
    op.drop_index('holders_user_id_foreign', table_name='holders')
    op.drop_table('holders')
    op.drop_index('poolstats_timestamp_index', table_name='poolstats')
    op.drop_table('poolstats')
    op.drop_index('ix_trades_id', table_name='trades')
    op.drop_index('ix_trades_launchpad_id', table_name='trades')
    op.drop_index('ix_trades_txid', table_name='trades')
    op.drop_table('trades')
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('uq_users_address', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_address', 'users', ['address'])
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'description')
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('launchpad_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('txid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('qty', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('amount', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('usd', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('type', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trades_pkey')
    )
    op.create_index('ix_trades_txid', 'trades', ['txid'], unique=False)
    op.create_index('ix_trades_launchpad_id', 'trades', ['launchpad_id'], unique=False)
    op.create_index('ix_trades_id', 'trades', ['id'], unique=False)
    op.create_table('poolstats',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('launchpad_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('token0_price', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('token1_price', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('tvl_usd', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('volume_24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('fee_tier', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('transactions_24h', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_transactions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('liquidity', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('price_change_1h', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('price_change_24h', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('price_change_7d', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('min_price_24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('max_price_24h', sa.NUMERIC(precision=36, scale=18), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='poolstats_pkey'),
    sa.UniqueConstraint('launchpad_id', 'timestamp', name='poolstats_launchpad_id_timestamp_unique')
    )
    op.create_index('poolstats_timestamp_index', 'poolstats', ['timestamp'], unique=False)
    op.create_table('holders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('launchpad_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('qty', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('prebond', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='holders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='holders_pkey'),
    sa.UniqueConstraint('launchpad_id', 'address', name='holders_launchpad_id_address_unique')
    )
    op.create_index('holders_user_id_foreign', 'holders', ['user_id'], unique=False)
    op.create_table('factories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=191), server_default=sa.text("'1'::character varying"), autoincrement=False, nullable=False),
    sa.Column('chainId', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('foundry', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('contract', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('lock', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('lock_abi', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('factory_abi', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('abi', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='factories_pkey')
    )
    op.create_table('launchpads',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('factory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract', sa.VARCHAR(length=44), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=44), autoincrement=False, nullable=True),
    sa.Column('pool', sa.VARCHAR(length=44), autoincrement=False, nullable=True),
    sa.Column('graph', sa.VARCHAR(length=600), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chainId', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('twitter', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('discord', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('telegram', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('livestreamId', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=191), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('kingofthehill', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='launchpads_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='launchpads_pkey')
    )
    op.create_index('ix_launchpads_user_id', 'launchpads', ['user_id'], unique=False)
    op.create_index('ix_launchpads_factory_id', 'launchpads', ['factory_id'], unique=False)
    # ### end Alembic commands ###
